#!/bin/bash
# mutants of the 8-bit read path (usage: TREE=<checkout> [PYTHON=<venv python>] mutants.sh [interp_qsa8.py|interp_dec8.py]); every one must report VIOLATIONS
HERE=$(cd "$(dirname "$0")" && pwd); SCRIPT=${1:-interp_qsa8.py}; T=${TREE:?set TREE to the checkout}; SRC=$T/exllamav3/modules/attention_fn/triton_paged.py; W=${MUT_DIR:-$HERE/_mut}; mkdir -p $W; cd $HERE; export TREE=$T
run(){ name=$1; shift; M=$W/tp_$name.py; cp $SRC $M; python3 - "$M" "$name" <<'PY'
import sys; p, n = sys.argv[1:3]; s = open(p).read()
muts = {
 "kt_head_off": [("    base = kv_head * (G * BITS)\n    row_words = tok_rows * (GPT * BITS)\n    qh = qwords + base\n    raw = tl.zeros((1, 1), tl.int32)  # replaced", "    base = kv_head * (G * BITS) + G * BITS\n    row_words = tok_rows * (GPT * BITS)\n    qh = qwords + base\n    raw = tl.zeros((1, 1), tl.int32)  # replaced")],
 "v_head_off": [("    base = kv_head * (G * BITS)\n    row_words = tok_rows * (GPT * BITS)\n    qh = qwords + base\n    raw = tl.zeros((1, 1), tl.int32)\n    pbase", "    base = kv_head * (G * BITS) + G * BITS\n    row_words = tok_rows * (GPT * BITS)\n    qh = qwords + base\n    raw = tl.zeros((1, 1), tl.int32)\n    pbase")],
 "kt_scale_stride": [("sc = tl.load(scales + tok_rows[None, :] * GPT + (sgb + garr)[:, None], mask = mask_n[None, :], other = 0.0)", "sc = tl.load(scales + tok_rows[None, :] * (GPT + 1) + (sgb + garr)[:, None], mask = mask_n[None, :], other = 0.0)")],
 "v_scale_stride": [("sc = tl.load(scales + tok_rows[:, None] * GPT + (sgb + garr)[None, :], mask = mask_n[:, None], other = 0.0)", "sc = tl.load(scales + tok_rows[:, None] * (GPT + 1) + (sgb + garr)[None, :], mask = mask_n[:, None], other = 0.0)")],
 "row_words_stride": [("    row_words = tok_rows * (GPT * BITS)\n    qh = qwords + base\n    raw = tl.zeros((1, 1), tl.int32)  # replaced", "    row_words = tok_rows * (GPT * BITS + 1)\n    qh = qwords + base\n    raw = tl.zeros((1, 1), tl.int32)  # replaced")],
 "dec_tok_k": [("            tok_rows = phys * page_size + page_off\n            k_tile = _qc_load_kt(k_cache, k_scales, tok_rows, kv_head, offs_d, offs_n < n_end, QCK, n_kv_heads, head_dim, HD_PAD)\n        else:\n            k_ptrs = k_cache + (((phys[None, :] * page_size + page_off[None, :]) * n_kv_heads + kv_head) * head_dim + offs_d[:, None])\n            if HD_PAD > head_dim:\n                k_tile = tl.load(k_ptrs, mask=(offs_n[None, :] < n_end) & d_mask[:, None], other=0.0)\n            else:\n                k_tile = tl.load(k_ptrs, mask=offs_n[None, :] < n_end, other=0.0)\n        scores = tl.dot(q_tile, k_tile) * scale\n        if SOFTCAP > 0.0:\n            scores_scaled = scores / SOFTCAP\n            scores = (2.0 / (1.0 + tl.exp(-2.0 * scores_scaled)) - 1.0) * SOFTCAP\n\n        valid = valid_row[:, None] & (offs_n[None, :] < n_end)\n        if CAUSAL:\n            valid = valid & (offs_n[None, :] <= q_abs[:, None])\n        if WINDOW_LEFT >= 0:\n            valid = valid & (offs_n[None, :] >= q_abs[:, None] - WINDOW_LEFT)", "            tok_rows = phys * page_size + page_off + page_size\n            k_tile = _qc_load_kt(k_cache, k_scales, tok_rows, kv_head, offs_d, offs_n < n_end, QCK, n_kv_heads, head_dim, HD_PAD)\n        else:\n            k_ptrs = k_cache + (((phys[None, :] * page_size + page_off[None, :]) * n_kv_heads + kv_head) * head_dim + offs_d[:, None])\n            if HD_PAD > head_dim:\n                k_tile = tl.load(k_ptrs, mask=(offs_n[None, :] < n_end) & d_mask[:, None], other=0.0)\n            else:\n                k_tile = tl.load(k_ptrs, mask=offs_n[None, :] < n_end, other=0.0)\n        scores = tl.dot(q_tile, k_tile) * scale\n        if SOFTCAP > 0.0:\n            scores_scaled = scores / SOFTCAP\n            scores = (2.0 / (1.0 + tl.exp(-2.0 * scores_scaled)) - 1.0) * SOFTCAP\n\n        valid = valid_row[:, None] & (offs_n[None, :] < n_end)\n        if CAUSAL:\n            valid = valid & (offs_n[None, :] <= q_abs[:, None])\n        if WINDOW_LEFT >= 0:\n            valid = valid & (offs_n[None, :] >= q_abs[:, None] - WINDOW_LEFT)")],
 "dec_tok_v": [("            tok_rows_v = phys * page_size + page_off\n            v_tile = _qc_load_v(v_cache, v_scales, tok_rows_v, kv_head, offs_d, offs_n < n_end, QCV, n_kv_heads, head_dim, HD_PAD)\n        else:\n            v_ptrs = v_cache + (((phys[:, None] * page_size + page_off[:, None]) * n_kv_heads + kv_head) * head_dim + offs_d[None, :])\n            if HD_PAD > head_dim:\n                v_tile = tl.load(v_ptrs, mask=(offs_n[:, None] < n_end) & d_mask[None, :], other=0.0)\n            else:\n                v_tile = tl.load(v_ptrs, mask=offs_n[:, None] < n_end, other=0.0)\n        acc = acc * alpha[:, None] + tl.dot(p.to(v_tile.dtype), v_tile)\n        m = m_new\n        l = l_new\n\n    if FINAL:", "            tok_rows_v = phys * page_size + page_off + page_size\n            v_tile = _qc_load_v(v_cache, v_scales, tok_rows_v, kv_head, offs_d, offs_n < n_end, QCV, n_kv_heads, head_dim, HD_PAD)\n        else:\n            v_ptrs = v_cache + (((phys[:, None] * page_size + page_off[:, None]) * n_kv_heads + kv_head) * head_dim + offs_d[None, :])\n            if HD_PAD > head_dim:\n                v_tile = tl.load(v_ptrs, mask=(offs_n[:, None] < n_end) & d_mask[None, :], other=0.0)\n            else:\n                v_tile = tl.load(v_ptrs, mask=offs_n[:, None] < n_end, other=0.0)\n        acc = acc * alpha[:, None] + tl.dot(p.to(v_tile.dtype), v_tile)\n        m = m_new\n        l = l_new\n\n    if FINAL:")],
 "midpoint": [("    mh = (1 << (BITS - 1)) - 0.5\n    inv_m = 1.0 / (1 << (BITS - 1))\n    return ((raw.to(tl.float32) - mh) * (scx.to(tl.float32) * inv_m)).to(tl.float16)\n\n\n@triton.jit\ndef _qc_load_v", "    mh = (1 << (BITS - 1)) - 0.0\n    inv_m = 1.0 / (1 << (BITS - 1))\n    return ((raw.to(tl.float32) - mh) * (scx.to(tl.float32) * inv_m)).to(tl.float16)\n\n\n@triton.jit\ndef _qc_load_v")],
}
for a, b in muts[n]:
    assert s.count(a) == 1, f"mutation {n} did not apply uniquely ({s.count(a)})"; s = s.replace(a, b)
open(p, "w").write(s)
PY
  [ $? = 0 ] || { echo "MUTANT $name: NOT APPLIED"; return; }
  TRITON_PAGED=$M MUT=$name nice -n 19 taskset -c 0-3 ${PYTHON:-python} $SCRIPT > $W/$SCRIPT.$name.log 2>&1; rc=$?
  echo "MUTANT $name: rc=$rc ($(grep -c . $W/$SCRIPT.$name.log) lines) $(grep -m1 -E 'VIOL|CLEAN' $W/$SCRIPT.$name.log)"
}
for m in $MUTS_FIRST kt_head_off v_head_off kt_scale_stride v_scale_stride row_words_stride midpoint; do run $m; done
echo "MUTANT bad_block_table: $(BADBT=1 nice -n 19 taskset -c 0-3 ${PYTHON:-python} $SCRIPT 2>&1 | grep -m1 -E 'VIOL|CLEAN')"
echo "MUTANT pool_one_page_short: $(SHORT=1 nice -n 19 taskset -c 0-3 ${PYTHON:-python} $SCRIPT 2>&1 | grep -m1 -E 'VIOL|CLEAN')"
echo "MUTANT wrong_bits_K4: $(KBITS=4 nice -n 19 taskset -c 0-3 ${PYTHON:-python} $SCRIPT 2>&1 | grep -m1 -E 'VIOL|CLEAN')"
